---
abstract: "This is an XML Parser that is based on a recursive function and RE's. It generates a JSON-like Perl data structure that can be easily traversed."
author:
  - 'Daniel Edward Graham'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.72, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: simpleXMLParse
no_index:
  directory:
    - t
    - inc
requires: {}
version: 2.8
